MvcMovie/Models/ErrorViewModel.cs
namespace MvcMovie.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcMovie/Models/HelloHandlerTest.cs
namespace MvcMovie.Models
{
    public class HelloHandlerTest
    {
        
        public string Hello()
        {
            return "Hello World";
        }


    }
}

MvcMovie/Models/MoveList.cs
using System.ComponentModel.DataAnnotations;

namespace MvcMovie.Models
{
    public class MoveList
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string? Genre { get; set; }
        public decimal Price { get; set; }
    }
}

MvcMovie/Controllers/HelloController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Xml.Linq;

namespace MvcMovie.Controllers
{
    public class HelloController : Controller
    {
        // GET: /HelloWorld/
        public string Index(string name = "Ronald", int numTimes = 1)
        {
            return HtmlEncoder.Default.Encode($"Hello {name}, NumTimes is: {numTimes}");

        }
       
        public ActionResult Welcome()
        {
            return View();

        }
        public ActionResult MoveList()
        {

            return View();

        }
    }
}

MvcMovie/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMovie.Models;
using System.Diagnostics;

namespace MvcMovie.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcMovie/Controllers/MoviesController.cs
using Azure;
using ManagerModel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Net.Http.Headers;
using Newtonsoft.Json;
using System.Text;
using System.Text.Json;

namespace _MvcMovie.Controllers
{
    public class MoviesController : Controller
    {
        List<MovieModel> movies = new List<MovieModel>();
        //private  JsonSerializerOptions _options; 
        static HttpClient client = new HttpClient();
        private readonly IHttpClientFactory httpClientFactory;
        public MoviesController(IHttpClientFactory _httpClientFactory)
        {
            httpClientFactory = _httpClientFactory;
        }
        // Infomacion tipo List
        public async Task<IActionResult> Index()
        {


            
                 
              



            var httpClient = httpClientFactory.CreateClient("APIDirection");
            // client.BaseAddress = new Uri("https://localhost:7075/");
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Add(HeaderNames.Accept, "application/json");

            var respose = await  httpClient.GetAsync("https://localhost:7075/todoitems").ConfigureAwait(false);
            if (respose.IsSuccessStatusCode)
            {
                var apiResponse = await respose.Content.ReadAsStringAsync();
                movies = JsonConvert.DeserializeObject<List<MovieModel>>(apiResponse);
            }
            //using (var httpClient = new HttpClient())
            //{
            //    using (var response = await httpClient.GetAsync("https://localhost:7075/todoitems"))
            //    {
            //        if (response.IsSuccessStatusCode) 
            //        {
            //            var apiResponse = await response.Content.ReadAsStringAsync();
            //            movies = JsonConvert.DeserializeObject<List<MovieModel>>(apiResponse);
            //        }
                    
            //    }
            //}
            return View(movies);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(MovieModel model)
        {

            try
            {
                MovieModel obj = new MovieModel();
                model.ReleaseDate = DateTime.Now;
                model.Id = Guid.NewGuid();
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

                    using (var response = await httpClient.PostAsync("https://localhost:7075/TodoPost", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        obj = JsonConvert.DeserializeObject<MovieModel>(apiResponse);
                    }
                }
            }catch(Exception ex) { }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> UpdateReservation(MovieModel _model)
        {
            MovieModel model = new MovieModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:7075/ChangeData" +_model.Id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    model = JsonConvert.DeserializeObject<MovieModel>(apiResponse);
                }
            }
            return View(model);
        }
    }
}

MvcMovie/Views/Hello/Index.cshtml
@{
    ViewData["Title"] = "Hello Page";
}

MvcMovie/Views/Hello/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome Page";
}


<p>Hello from our View Template!</p>

MvcMovie/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcMovie/Views/Movies/Create.cshtml
<div>
    <div class="row">
        <div class="col-10">
            <h1>New Movie</h1>
        </div>
    </div>
    <br />
    <div class="col">
        <form asp-controller="Movies" asp-action="Create">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="floatingInput" placeholder="Title of the list" name="Title">
                <label for="floatingInput">Name of the List</label>
            </div>
            <div class="form-floating">
                <input class="form-control" placeholder="Genero" id="floatingTextarea" name="Genre" />
                <label for="floatingTextarea">Genero</label>
            </div>
            <br />
            <div>
                <button type="submit" class="btn btn-primary">Create Movie</button>
            </div>
        </form>
    </div>
</div>

MvcMovie/Views/Movies/Edit.cshtml
@model ManagerModel.Models.MovieModel

<h2>Update a Reservation <a asp-action="Index" class="btn btn-sm btn-secondary">Back</a></h2>
<form method="post">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input class="form-control" asp-for="Title" readonly />
    </div>
    <div class="form-group">
        <label asp-for="Genre"></label>
        <input class="form-control" asp-for="Genre" />
    </div>
    <div class="form-group">
        <label asp-for="ReleaseDate"></label>
        <input class="form-control" asp-for="ReleaseDate" readonly />
    </div>
    <div class="text-center panel-body">
        <button type="submit" class="btn btn-sm btn-primary">Update</button>
    </div>
</form>}

MvcMovie/Views/Movies/Index.cshtml
@model IEnumerable<ManagerModel.Models.MovieModel>

@{
    ViewData["Title"] = "Index";
   //  Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Move List</h1>

<p style="text-align:right;margin-right:20px;">
    <a class="btn btn-outline-primary" asp-controller="Movies" asp-action="Create">Create New</a>
</p>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReleaseDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Genre)
                </th>
                
                <th></th>
                <th>Edit Action</th>
                <th>Details Action</th>
                <th>Delete Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReleaseDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Genre)
                    </td>
                 
                    <td>
                    <td class="text-center">
                        <a asp-action="UpdateReservation" class="btn btn-outline-primary" asp-route-id="@item.Id" name="Id">Edit</a>
                    </td>
                    <td class="text-center">
                        <a asp-action="Details" class="btn btn-outline-info" asp-route-id="@item.Id">Details</a>
                    </td>
                    <td class="text-center">
                        <a asp-action="Delete" class="btn btn-outline-danger" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MvcMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcMovie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcMovie.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcMovie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcMovie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcMovie/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcMovie.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom boxshadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" aasp-controller="Hello" asp-action="Welcome">Movie App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bstarget=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Hello" asp-action="Welcome">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index">Move List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Movie App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>